import Flag from '@/components/common/Flag';
import Nav from '@/components/dashboard/nav/nav';
import Sidebar from '@/components/dashboard/side-bar/side-bar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen flex">
      <Sidebar />
      <div className="flex-1 py-2">
        <Nav />
        <div className="hidden sm:block">
          <Flag />
        </div>
        {children}
      </div>
    </main>
  );
}